AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  IgnoredPatterns: ['^#']
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'
    - 'config/initializers/*.rb'
    - 'config/routes.rb'

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

#Layout/HashAlignment:
#  EnforcedColonStyle:

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'app/graphql/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
    - 'app/models/concerns/**/*'
  Max: 15

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/DoubleNegation:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $kafka_producer
    - $kafka
